ui: Input(textarea) 컴포넌트 및 관련 세부기능 생성
Team-TIFY/TIFY-CLIENT pull request #23
Opened 2023-07-13 05:24 UTC by choyeon2e

2023-07-13 07:59 UTC, eugene028 commented
작업 끝나면 리뷰어에 추가해주셔~

2023-07-14 18:02 UTC, eugene028 requested changes
초연!! 수고했다우.
우리가 atom 컴포넌트를 만드는 이유 중의 하나가 재사용 + 미래 구현에만 집중하기 위해서인데
현재 초연이의 `textArea`에는 입력받았을 때 그 입력 이벤트를 관리할 수 있는 상태를 얻기 어려운 것 같아!
그래서 textarea에서 관리하는 값을 `value`로 넘겨주던가,`ref` 를 이용하여 textarea의 dom을 조작할 수 있도록 외부에서 props를 받아와야 할 것 같아요!!
main 컴포넌트 개발 시 어떻게 하면 textarea에 입력되는 데이터를 백엔드에게 쉽게 넘겨줄 수 있을까? 고민해서 이 부분만 수정해주면 좋을 것 같아오우~ 

```js
<StyledTextArea
  value={value}
  ref={ref} //생략가능 (선택)
  onChange = {onChange}
  {...props}
/>
```

2023-07-14 18:02 UTC, eugene028 commented on src/components/atoms/Input/index.tsx
> +const INPUT_TYPE: InputVariantType = {
사실 요렇게 간단한건 `InputVariantType`을 작성하지 않아도 되지만 확장성을 고려한다면 좋은 코드 같아요 👍

2023-07-14 18:02 UTC, eugene028 commented on src/components/atoms/Input/index.tsx
> +    children
`children`의 네이밍이 살짝 애매한것 같다!
초연이가 의도한 건 아래 코드인가?
```js
<TextArea variant = {'withInst'} >설명입력</TextArea>
```
하지만 이렇게 작성하는 것보다는 , 설명을 입력할 수 있다는 것을 나타내기 위해 `children` 을 이용하기보다는 `explanation` 을 이용하고, 필수적으로 받아야 하는 친구는 아니니까 이렇게 바꿔볼 수 있을 듯??
```js
interface InputProps extends React.ComponentProps<'div'>{
  variant: InputVariant;
  explanation: string;
}
```
그래서 컴포넌트의 props로 받아오는거지!

2023-07-14 18:02 UTC, eugene028 commented on src/components/atoms/Input/index.tsx
> +    width: 284px;
<img width="439" alt="스크린샷 2023-07-15 오전 2 53 07" src="https://github.com/Team-TIFY/TIFY-CLIENT/assets/67894159/804f666b-9fa6-4b9e-a9c8-26bd63572bdb">

애매하게 가운ㄷ데 정렬이 안 맞는 것 같아서 여기에 이 속성을 주면 어떨까요!
```js
display: flex;
align-items: center;
```

2023-07-14 18:02 UTC, eugene028 commented on src/main.tsx
> -  </BrowserRouter>
헉!! 이거는 전의 파일로 되돌려 주세요~~ 글로벌 ui 세팅해둔거라서!! 
```js
<Global styles={globalStyle}/>
      <ThemeProvider theme = {theme}>
        <RecoilRoot>
          <App />
        </RecoilRoot>
      </ThemeProvider>
```
다시 추가해주기!

2023-07-14 18:02 UTC, eugene028 commented on src/styles/theme/global.ts
코드 읽어보니까 47번줄에 `import { palette } from './palette`` 가 옮겨져있던데 이거 원래 자리에 되돌려주세여!

2023-07-14 18:03 UTC, eugene028 commented on .storybook/preview.ts
> -import type { Preview } from "@storybook/react";
초연이 vscode에서 쓰는 eslint에 설정이 있나??
`""`을 `''`로 바꿔주는 것 같네 ! 
우리 로컬 eslint로만 작동해야 하는데 내가 세팅을 잘못한 거 같구만... 고쳐보겟씁니당

2023-07-14 18:05 UTC, eugene028 commented on package.json
> -    "react-router-dom": "^6.13.0",
헉 이건 왜 버전업이 된걸까요??

2023-07-14 18:05 UTC, eugene028 commented on src/components/atoms/Input/index.tsx
> +interface InputProps extends React.ComponentProps<'div'>{
TextArea에 관련된 컴포넌트이기 때문에 받아오는 props를 `TextareaHTMLAttributes<HTMLTextAreaElement>`를 사용해보면 어떨까요!

2023-07-14 18:10 UTC, eugene028 commented on src/components/atoms/Input/index.tsx
> +export const TextArea = (
폴더명과 컴포넌트 이름을 통일해주세용 >.< !!

2023-07-15 10:06 UTC, choyeon2e commented on package.json
> -    "react-router-dom": "^6.13.0",
> 헉 이건 왜 버전업이 된걸까요??

움.. 처음에 시작할 때 yarn dev 안되는 오류 났던거 때문에 막 install 해보고 이랬던거 때문인가?.. 정확한 이유는 잘 모르겠다 ㅜ!

2023-07-16 14:44 UTC, merged